version: '3.5'

services:

  redis:
    image: redis
    command: "redis-server --save \"\" --appendonly no"
    ports:
      - "6379:6379"
    networks:
      - compose-services-network

  gateway-internal:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/gateway-internal:latest"
    depends_on:
      - redis
    volumes:
      - "${GCP_API_KEY}:/secrets/analytics-api-key"
      - "${ANALYTICS_CONFIG}:/config/online-services-analytics-config"
    command:
      - dotnet
      - "GatewayInternal.dll"
      - "--redis_connection_string=redis:6379"
      - "--analytics.endpoint=http://analytics-esp:8080/v1/event"
      - "--analytics.allow-insecure-endpoint"
      - "--analytics.config-file-path=/config/online-services-analytics-config"
      - "--analytics.gcp-key-path=/secrets/analytics-api-key"
      - "--analytics.environment=testing"
    networks:
      - compose-services-network

  gateway:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/gateway:latest"
    depends_on:
      - redis
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    volumes:
      - "${GCP_API_KEY}:/secrets/analytics-api-key"
      - "${ANALYTICS_CONFIG}:/config/online-services-analytics-config"
    command:
      - dotnet
      - "Gateway.dll"
      - "--grpc_service_port=4040"
      - "--redis_connection_string=redis:6379"
      - "--analytics.endpoint=http://analytics-esp:8080/v1/event"
      - "--analytics.allow-insecure-endpoint"
      - "--analytics.config-file-path=/config/online-services-analytics-config"
      - "--analytics.gcp-key-path=/secrets/analytics-api-key"
      - "--analytics.environment=testing"
    networks:
      - compose-services-network

  gateway-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4040:4040"
      - "8080:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_ANALYTICS_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=gateway.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://gateway:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  party:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/party:latest"
    depends_on:
      - redis
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    volumes:
      - "${GCP_API_KEY}:/secrets/analytics-api-key"
      - "${ANALYTICS_CONFIG}:/config/online-services-analytics-config"
    command:
      - dotnet
      - "Party.dll"
      - "--grpc_service_port=4040"
      - "--redis_connection_string=redis:6379"
      - "--analytics.endpoint=http://analytics-esp:8080/v1/event"
      - "--analytics.allow-insecure-endpoint"
      - "--analytics.config-file-path=/config/online-services-analytics-config"
      - "--analytics.gcp-key-path=/secrets/analytics-api-key"
      - "--analytics.environment=testing"
    networks:
      - compose-services-network

  party-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4041:4040"
      - "8081:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_ANALYTICS_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=party.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://party:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  playfab-auth:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/playfab-auth:latest"
    environment:
      PLAYFAB_SECRET_KEY: "${PLAYFAB_SECRET_KEY}"
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
    volumes:
      - "${GCP_API_KEY}:/secrets/analytics-api-key"
      - "${ANALYTICS_CONFIG}:/config/online-services-analytics-config"
    command:
      - dotnet
      - "PlayfabAuth.dll"
      - "--grpc_service_port=4040"
      - "--playfab_title_id=${PLAYFAB_TITLE_ID}"
      - "--spatial_project=${SPATIAL_PROJECT_NAME}"
      - "--analytics.endpoint=http://analytics-esp:8080/v1/event"
      - "--analytics.allow-insecure-endpoint"
      - "--analytics.config-file-path=/config/online-services-analytics-config"
      - "--analytics.gcp-key-path=/secrets/analytics-api-key"
      - "--analytics.environment=testing"
    networks:
      - compose-services-network

  playfab-auth-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "4042:4040"
      - "8082:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_ANALYTICS_ENDPOINT}:/secrets/json/services-endpoint.json"
    command:
      - "--service=playfab-auth.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--http_port=8080"
      - "--http2_port=4040"
      - "--backend=grpc://playfab-auth:4040"
      - "--service_account_key=/secrets/json/services-endpoint.json"
    networks:
      - compose-services-network

  matcher:
    image: "gcr.io/${GOOGLE_PROJECT_ID}/sample-matcher:latest"
    environment:
      SPATIAL_REFRESH_TOKEN: "${SPATIAL_REFRESH_TOKEN}"
      SPATIAL_PROJECT: "${SPATIAL_PROJECT_NAME}"
      GATEWAY_SERVICE_TARGET: "gateway-internal:4040"
    volumes:
      - "${GCP_API_KEY}:/secrets/analytics-api-key"
      - "${ANALYTICS_CONFIG}:/config/online-services-analytics-config"
    command:
      - "--analytics.endpoint=http://analytics-esp:8080/v1/event"
      - "--analytics.allow-insecure-endpoint"
      - "--analytics.config-file-path=/config/online-services-analytics-config"
      - "--analytics.gcp-key-path=/secrets/analytics-api-key"
      - "--analytics.environment=testing"
    networks:
      - compose-services-network

  analytics-esp:
    image: "gcr.io/endpoints-release/endpoints-runtime:1.38.0"
    ports:
      - "8083:8080"
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_ANALYTICS_ENDPOINT}:/secrets/json/analytics-endpoint.json"
    command:
      - "--http_port=8080"
      - "--backend=analytics:8080"
      - "--service=analytics.endpoints.${GOOGLE_PROJECT_ID}.cloud.goog"
      - "--rollout_strategy=managed"
      - "--service_account_key=/secrets/json/analytics-endpoint.json"
    networks:
      - compose-services-network

  analytics:
    volumes:
      - "${GOOGLE_SECRET_KEY_JSON_ANALYTICS_GCS_WRITER}:/secrets/json/analytics-gcs-writer.json"
      - "${GOOGLE_SECRET_KEY_P12_ANALYTICS_GCS_WRITER}:/secrets/p12/analytics-gcs-writer.p12"
    image: "gcr.io/${GOOGLE_PROJECT_ID}/analytics-endpoint:latest"
    environment:
      GOOGLE_SECRET_KEY_JSON_ANALYTICS_GCS_WRITER: "/secrets/json/analytics-gcs-writer.json"
      GOOGLE_SECRET_KEY_P12_ANALYTICS_GCS_WRITER: "/secrets/p12/analytics-gcs-writer.p12"
      ANALYTICS_BUCKET_NAME: "${GOOGLE_PROJECT_ID}-analytics"
      GOOGLE_PROJECT_ID: "${GOOGLE_PROJECT_ID}"
      GOOGLE_SERVICE_ACCOUNT_EMAIL_ANALYTICS_GCS_WRITER: "analytics-gcs-writer@${GOOGLE_PROJECT_ID}.iam.gserviceaccount.com"
    networks:
      - compose-services-network

networks:
  compose-services-network:
    name: compose-services-network
