kind: Service
apiVersion: v1
metadata:
  name: playfab-auth
spec:
  selector:
    app: playfab-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4040
  type: LoadBalancer
  loadBalancerIP: "[your PlayFab Auth IP address]"