kind: Service
apiVersion: v1
metadata:
  name: party
spec:
  selector:
    app: party
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4040
  type: LoadBalancer
  loadBalancerIP: "[your Party IP address]"