apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-internal
  labels:
    app: gateway-internal
spec:
  replicas: 1
  selector:
      matchLabels:
        app: gateway-internal
  template:
    metadata:
      labels:
        app: gateway-internal
    spec:
      containers:
      - name: gateway-internal
        image: gcr.io/[your Google project name]/gateway-internal
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4040
          protocol: TCP
        - containerPort: 8080
          name: 'metrics'
          protocol: TCP
        env:
        - name: SPATIAL_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: spatialos-service-account
              key: service-account.txt
        - name: REDIS_CONNECTION_STRING
          valueFrom:
            configMapRef:
              name: online-services-config
              key: redis.connection-string